#+Author: Diana Muñoz @DIANAIMC, Mariano Alcaraz @MarianoAlcarazAguilar, Sebastián Murillo @S-murilloG

*** Pasos para todo
1. Crear el contenedor
2. Extraer los datos y meterlos al contenedor
3. Sacar los datos de mongo a nuestra máquina en formato json

# SpotifyAPI_tests
Proyecto Final: Bases de Datos No Relacionales

* Introducción
  Este es el repositorio con el contenido del proyecto final para la clase de Bases de Datos No Relacionales de la Licenciatura en Ciencia de Datos del ITAM. 
  
* Objetivo
  Buscar alguna API que llame la atención al equipo, con esta API, conectarla através de python con una base de datos MongoDB. Posteriormente, hacer un ETL que cargue la base de datos procesada a una base de datos columnar y a una base de datos estilo grafo; evidentemente las transformaciones y los subconjuntos de datos ocupados serán diferentes para cada base de datos ya que tienen fines diferentes cada una.

* Desarrollo

A continuación explicaremos detalladamente el código por partes. Si se desea correr todo el proyecto, ejecute los siguientes comandos:

#+begin_src shell
./requirements.txt
./main.sh
#+end_src

Una vez, ejecutado, ya estarán extraídos e insertados todos los datos tanto en Mongo, Monet y Neo4j

** Objetivos:
Aquí poner lo que ponga el profe :)

*** Por hacer:
**** Insertar datos de una API pública a Mongo
  - Obtener datos de la API de Spotify
    - Revisar cómo obtener el token dentro del script
    - ~~Reducir el tiempo de ejecución (extraer 500 datos de cada objeto nos cuesta 3.5 minutos)~~
    - ~~Ver porqué al extraer los objetos individualmente si permite hasta 500, pero en conjunto máximo 200 de c/u~~
    - ~~¿Podemos lograr meter 1000 de cada uno?~~
    - ~~Averiguar si hay repetidos, si sí, eliminarlos~~
    - Verificar que si se incerten correctamente los datos a Mongo
    - Hacer 3 queries
**** Insertar datos de Mongo a Monet
**** Insertar datos de Monet (o Mongo) a Neo4j
